from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import HexColor
from datetime import datetime


def generate_pdf(
    filename,
    match_score,
    semantic_score,
    verdict,
    matched_skills,
    missing_skills,
    recommendations
):
    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    title = styles["Title"]
    title.alignment = TA_CENTER
    title.textColor = HexColor("#1E3A8A")

    heading = styles["Heading2"]
    heading.textColor = HexColor("#2563EB")

    normal = styles["Normal"]

    elements = []

    # Title
    elements.append(Paragraph("AI Resume Screening Report", title))
    elements.append(Spacer(1, 15))

    # Summary
    elements.append(Paragraph("<b>Resume Summary</b>", heading))
    elements.append(Paragraph(f"<b>ATS Score:</b> {match_score:.2f}%", normal))
    elements.append(Paragraph(f"<b>Semantic Score:</b> {semantic_score:.2f}%", normal))
    elements.append(Paragraph(f"<b>Overall Verdict:</b> {verdict}", normal))
    elements.append(Spacer(1, 15))

    # Matched Skills
    elements.append(Paragraph("Matched Skills", heading))

    if matched_skills:
        for skill in matched_skills:
            elements.append(
                Paragraph(f"✓ {skill.title()}", normal)
            )
    else:
        elements.append(Paragraph("No matched skills.", normal))

    elements.append(Spacer(1, 15))

    # Missing Skills
    elements.append(Paragraph("Missing Skills", heading))

    if missing_skills:
        for skill in missing_skills:
            elements.append(
                Paragraph(f"✗ {skill.title()}", normal)
            )
    else:
        elements.append(
            Paragraph("No missing skills.", normal)
        )

    elements.append(Spacer(1, 15))

    # Recommendations
    elements.append(
        Paragraph("AI Recommendations", heading)
    )

    if recommendations:
        for item in recommendations:
            elements.append(
                Paragraph(f"• {item}", normal)
            )
    else:
        elements.append(
            Paragraph(
                "Excellent resume. No recommendations.",
                normal
            )
        )

    elements.append(Spacer(1, 20))

    # Footer
    date = datetime.now().strftime("%d-%m-%Y %I:%M %p")

    elements.append(
        Paragraph(
            "<b>Generated by AI Resume Screening System</b>",
            normal
        )
    )

    elements.append(
        Paragraph(
            f"Generated on: {date}",
            normal
        )
    )

    doc.build(elements)